import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';
import {compileTown} from '../src/layout.js';import {CASES,KIT_VERSION,validateSpec,streetMetrics} from '../src/kit.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),out=path.join(root,'evidence/v4'),publicOut=path.join(root,'public/data/v4');fs.mkdirSync(out,{recursive:true});fs.mkdirSync(publicOut,{recursive:true});
const quote=s=>"'"+s.replaceAll("'","'\\''")+"'";
function remote(script,input){return new Promise((resolve,reject)=>{const child=spawn('ssh',['-o','BatchMode=yes','-o','ConnectTimeout=15','-o','ControlMaster=no','-o','ControlPath=none','-o','UpdateHostKeys=no',process.env.FF_GENERATION_HOST||'shouyun-4090',`python3 -c ${quote(script)}`]);let stdout='',stderr='';child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);child.on('error',reject);child.on('close',code=>{try{if(code)throw new Error(stderr.slice(-600));resolve(JSON.parse(stdout));}catch(e){reject(new Error('Remote operation failed: '+e.message));}});child.stdin.end(JSON.stringify(input));});}
const controller=fs.readFileSync(path.join(root,'tools/remote/remote_small_server.py'),'utf8'),infer=fs.readFileSync(path.join(root,'tools/remote/remote_infer.py'),'utf8');
const snapshotScript=`import subprocess,json,urllib.request\nrows=subprocess.check_output(['nvidia-smi','--query-gpu=index,uuid,memory.used,memory.free','--format=csv,noheader,nounits'],text=True).strip().splitlines()\ngpus=[dict(zip(['index','uuid','usedMiB','freeMiB'],[int(v.strip()) if i in (0,2,3) else v.strip() for i,v in enumerate(r.split(','))])) for r in rows]\napps=subprocess.check_output(['nvidia-smi','--query-compute-apps=pid,gpu_uuid,process_name,used_memory','--format=csv,noheader,nounits'],text=True).strip().splitlines()\nprocesses=[{'pid':int(r.split(',')[0]),'gpu':r.split(',')[1].strip(),'name':r.split(',')[2].strip(),'usedMiB':int(r.split(',')[3])} for r in apps if r.strip()]\nprint(json.dumps({'gpus':gpus,'processes':processes}))`;
const enumString=a=>({type:'string',enum:a}),num=(min,max)=>({type:'number',minimum:min,maximum:max});
const schema={type:'object',additionalProperties:false,required:['version','kit','title','subtitle','road','buildings'],properties:{version:{type:'integer',enum:[4]},kit:enumString([KIT_VERSION]),title:{type:'string'},subtitle:{type:'string'},road:{type:'object',additionalProperties:false,required:['width','bend','sway'],properties:{width:{type:'number',enum:[5.4,5.6,5.8,6.0,6.2,6.4,6.6,6.8,7.0,7.2]},bend:{type:'number',enum:[-2.2,-1.6,-.8,0,.8,1.6,2.2]},sway:{type:'number',enum:[-.6,-.3,0,.3,.6]}}},buildings:{type:'array',minItems:6,maxItems:10,items:{type:'object',additionalProperties:false,required:['kind','name','side','z','width','depth','setback','assembly'],properties:{kind:enumString(['bakery','florist','inn','toys','cafe','books','home','apothecary']),name:{type:'string'},side:enumString(['left','right']),z:{type:'number',enum:Array.from({length:65},(_,i)=>-8.5+i*.5)},width:{type:'number',enum:[4.8,5.2,5.6,6.0,6.4]},depth:{type:'number',enum:[4.0,4.4,4.8,5.2]},setback:{type:'number',enum:[0,.25,.5,.75,1]},assembly:{type:'object',additionalProperties:false,required:['stories','roof','roofRise','bay','awning','balcony','chimney'],properties:{stories:{type:'integer',enum:[2,3]},roof:enumString(['clay','teal']),roofRise:{type:'number',enum:[2.8,3.2,3.6,4.0]},bay:enumString(['none','octagonal']),awning:enumString(['none','striped']),balcony:enumString(['none','timber']),chimney:enumString(['none','tall-stone'])}}}}}}};
const system=`You plan original walkable FF9-inspired royal-city streets using one locked existing art kit. Return ONLY the JSON matching the schema. No image generation, asset URLs, mesh code, textures, new module kinds or free-form geometry. You choose road width/curvature and buildings' placement AND combinations of modules. All streets use the same weathered plaster, hewn wood, clay/teal tiles, leaded recessed windows and arch doors.\nThe walking route runs from z=30 to z=-14; the plaza is beyond z=-14. Place buildings z from -8.5 to 23.5. Buildings face the road on left/right. Building width runs ALONG z. Depth extends away from the road. Same-side neighbor z gaps must exceed (widthA+widthB)/2+1.0 meters, preferably 7–9m. Limit one side to at most 5 buildings. E.g. five per side can fit near z=23,15,7,-1,-8. Keep two sides visibly staggered by 0.5–1.0m if possible. Different setback creates varying frontage. Moderate bends are safest.\nAvailable dimensional catalogue: width=4.8/5.2/5.6/6.0/6.4 meters; depth=4.0/4.4/4.8/5.2; setback=0/0.25/0.5/0.75/1.0; roofRise=2.8/3.2/3.6/4.0. A bay and balcony MUST NOT occur on the same building: they occupy the same facade space. These are library constraints. Use BOTH roof materials, varied dimensions, and at least 3 distinct assembly combinations per street. A timber balcony, octagonal bay, high stone chimney, striped awning and 2/3 stories change silhouettes. Do not assign every facade every feature. Use Chinese title, subtitle and shop names. Preserve all specific numeric requirements from the user. Height is derived from stories, not chosen by you.`;
fs.writeFileSync(path.join(out,'schema.json'),JSON.stringify(schema,null,2));fs.writeFileSync(path.join(out,'system-prompt.txt'),system);fs.writeFileSync(path.join(out,'cases.json'),JSON.stringify(CASES,null,2));
function assets(){const dir=path.join(root,'public/assets/v3');return Object.fromEntries(fs.readdirSync(dir).sort().map(name=>[name,createHash('sha256').update(fs.readFileSync(path.join(dir,name))).digest('hex')]));}
const assetsBefore=assets(),before=await remote(snapshotScript,{});fs.writeFileSync(path.join(out,'resource-before.json'),JSON.stringify(before,null,2));
let started=false,startInfo,records=[],failure=null;
try{
 const status=await remote(controller,{action:'status'});if(status.pid)throw new Error('The small-model experiment is already running; preserve the other generation task.');
 startInfo=await remote(controller,{action:'start'});if(startInfo.reused)throw new Error('Another task started the small model concurrently; preserve its process.');started=true;console.log(JSON.stringify({phase:'model-ready',gpu:startInfo.gpu,pid:startInfo.pid,modelBytes:startInfo.modelBytes}));
 const loaded=await remote(snapshotScript,{});fs.writeFileSync(path.join(out,'resource-loaded.json'),JSON.stringify(loaded,null,2));
 for(const c of CASES){const caseSchema=structuredClone(schema),count={residential:6,market:10,workshops:8}[c.id];caseSchema.properties.buildings.minItems=caseSchema.properties.buildings.maxItems=count;caseSchema.properties.road.properties.width.enum={residential:[5.4,5.6,5.8],market:[6.6,6.8,7.0,7.2],workshops:[6.0,6.2,6.4]}[c.id];fs.writeFileSync(path.join(out,c.id+'-schema.json'),JSON.stringify(caseSchema,null,2));let messages=[{role:'system',content:system},{role:'user',content:c.brief}],attempts=[],accepted=null;
  for(let attempt=1;attempt<=3;attempt++){
   const reply=await remote(infer,{endpoint:'http://127.0.0.1:8087',model:'ff7-layout-4b',messages,seed:c.seed+attempt-1,schema:caseSchema});let error=null;
   try{if(!reply.ok)throw new Error('inference failed');const spec=JSON.parse(reply.content);spec.provenance={source:'qwen3-4b-instruct-2507-q4_k_m',caseId:c.id,seed:c.seed+attempt-1,attempt,training:'none',newImageGenerationCalls:0,kit:KIT_VERSION,placement:'model-preferences+isotonic-constraint-packing'};validateSpec(spec,c.id);const plan=compileTown(spec);spec.realization={placementAlgorithm:'least-squares-isotonic-roadside-packing',positions:plan.buildings.map(b=>({id:b.id,side:b.side,requestedZ:b.requestedZ,realizedZ:b.routeZ,x:b.x,z:b.z}))};accepted={spec,metrics:streetMetrics(spec,plan)};}catch(e){error=e.message;}
   attempts.push({attempt,...reply,validatorError:error});fs.writeFileSync(path.join(out,c.id+'-attempts.json'),JSON.stringify({brief:c.brief,attempts},null,2));console.log(JSON.stringify({case:c.id,attempt,accepted:!!accepted,error,seconds:reply.elapsedSeconds}));
   if(accepted)break;messages=[{role:'system',content:system},{role:'user',content:c.brief},{role:'assistant',content:reply.content||'{}'},{role:'user',content:'The validator rejected your JSON: '+error+'. Correct an EXISTING building rather than adding buildings: exactly '+count+' required. Keep all original numeric requirements. Return a whole corrected JSON.'}];
  }
  if(!accepted)throw new Error(c.id+' failed all bounded attempts');
  fs.writeFileSync(path.join(publicOut,c.id+'.json'),JSON.stringify(accepted.spec,null,2));records.push({id:c.id,label:c.label,path:'data/v4/'+c.id+'.json',attempts:attempts.length,metrics:accepted.metrics});
 }
}catch(e){failure=e.message;throw e;}
finally{
 let stopped=null;if(started){stopped=await remote(controller,{action:'stop'});console.log(JSON.stringify({phase:'model-stopped',...stopped}));}
 const after=await remote(snapshotScript,{});fs.writeFileSync(path.join(out,'resource-after.json'),JSON.stringify(after,null,2));
 const assetsAfter=assets();const missingSharedPids=before.processes.filter(p=>!after.processes.some(q=>q.pid===p.pid)).map(p=>p.pid);
 const summary={passed:!failure&&records.length===3,model:'Qwen3-4B-Instruct-2507 Q4_K_M',training:'none',newImageGenerationCalls:0,assetsBefore,assetsAfter,assetsUnchanged:JSON.stringify(assetsBefore)===JSON.stringify(assetsAfter),records,resource:{startInfo,stopped,missingSharedPids},failure};fs.writeFileSync(path.join(out,'generation-summary.json'),JSON.stringify(summary,null,2));
 if(summary.passed){fs.writeFileSync(path.join(publicOut,'manifest.json'),JSON.stringify({version:4,kit:KIT_VERSION,defaultStreet:'residential',streets:records,newImageGenerationCalls:0,assets:assetsBefore},null,2));}
}
