import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {compileTown} from '../src/layout.js';
const url=new URL('../public/assets/characters/chocobo/chocobo-v1.glb',import.meta.url),buffer=fs.readFileSync(url);assert.equal(buffer.toString('utf8',0,4),'glTF');assert.equal(buffer.readUInt32LE(4),2);assert.equal(buffer.readUInt32LE(8),buffer.length);
const jsonLength=buffer.readUInt32LE(12),gltf=JSON.parse(buffer.subarray(20,20+jsonLength).toString().trim()),binary=buffer.subarray(20+jsonLength+8);
const sizes={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4},counts={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16};
function readAccessor(id){const a=gltf.accessors[id],v=gltf.bufferViews[a.bufferView],width=counts[a.type],size=sizes[a.componentType],stride=v.byteStride||width*size,offset=(v.byteOffset||0)+(a.byteOffset||0),view=new DataView(binary.buffer,binary.byteOffset,binary.byteLength),fn={5120:'getInt8',5121:'getUint8',5122:'getInt16',5123:'getUint16',5125:'getUint32',5126:'getFloat32'}[a.componentType],rows=[];for(let i=0;i<a.count;i++){const row=[];for(let j=0;j<width;j++){let x=view[fn](offset+i*stride+j*size,true);if(a.normalized)x/=a.componentType===5121?255:a.componentType===5123?65535:1;assert.ok(Number.isFinite(x));row.push(x);}rows.push(row);}return rows;}
assert.equal(gltf.skins.length,1);assert.equal(gltf.skins[0].joints.length,24);assert.deepEqual(gltf.animations.map(a=>a.name).sort(),['Chirp','Flap','Idle','Walk']);
let vertices=0,triangles=0;for(const mesh of gltf.meshes)for(const p of mesh.primitives){const weights=readAccessor(p.attributes.WEIGHTS_0),joints=readAccessor(p.attributes.JOINTS_0);for(let i=0;i<weights.length;i++){assert.ok(Math.abs(weights[i].reduce((a,b)=>a+b,0)-1)<.005);assert.ok(joints[i].every(j=>j>=0&&j<24));}vertices+=weights.length;triangles+=(p.indices!==undefined?gltf.accessors[p.indices].count:weights.length)/3;}
const clips=[];for(const a of gltf.animations){let seconds=0,changes=0,maxSeam=0;for(const c of a.channels){const sampler=a.samplers[c.sampler],times=readAccessor(sampler.input).flat(),values=readAccessor(sampler.output);assert.ok(times.every((t,i)=>i===0||t>times[i-1]));seconds=Math.max(seconds,times.at(-1));const first=values[0],last=values.at(-1);let seam=Math.max(...first.map((x,i)=>Math.abs(x-last[i])));if(c.target.path==='rotation'){for(const v of values)assert.ok(Math.abs(Math.hypot(...v)-1)<.006);seam=Math.min(seam,Math.max(...first.map((x,i)=>Math.abs(x+last[i]))));}maxSeam=Math.max(maxSeam,seam);if(values.some(v=>v.some((x,i)=>Math.abs(x-first[i])>.003)))changes++;}assert.ok(changes>=3,'clip must animate independent joints');if(['Idle','Walk'].includes(a.name))assert.ok(maxSeam<.002,'loop seam '+a.name+': '+maxSeam);clips.push({name:a.name,seconds,animatedChannels:changes,loopSeam:maxSeam});}
const build=JSON.parse(fs.readFileSync(new URL('../evidence/chocobo/build-report.json',import.meta.url)));assert.ok(build.allWeightsNormalized);for(const c of Object.values(build.groundSamples)){assert.ok(c.minimumToeZ>-.002);assert.ok(c.maximumLowestToeZ<.008);}assert.equal(build.toesPerFoot,3);for(const side of ['L','R'])for(let i=0;i<3;i++)assert.ok(gltf.nodes.some(n=>n.name==='Toe_'+side+'_'+i));
const streets=['residential','market','workshops'].map(id=>{const plan=compileTown(JSON.parse(fs.readFileSync(new URL('../public/data/v4/'+id+'.json',import.meta.url))));assert.ok(plan.people.some(p=>p.species==='chocobo'));return id;});
const report={passed:true,assetSha256:createHash('sha256').update(buffer).digest('hex'),bytes:buffer.length,joints:gltf.skins[0].joints.length,meshes:gltf.meshes.length,vertices,triangles,images:gltf.images.length,clips,groundSamples:build.groundSamples,toesPerFoot:build.toesPerFoot,streets,sharedAsset:true};fs.writeFileSync(new URL('../evidence/chocobo/asset-verification.json',import.meta.url),JSON.stringify(report,null,2));console.log(report);
