import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {compileTown,canOccupy} from '../src/layout.js';
import {makeCastStage} from '../src/cast-stage.js';
const models=['moogle','mage','chocobo'].map(name=>{const m=JSON.parse(fs.readFileSync(new URL('../art-direction/'+name+'/manifest.json',import.meta.url))),data=fs.readFileSync(new URL('../'+m.asset,import.meta.url)),sha=createHash('sha256').update(data).digest('hex');assert.equal(sha,m.sha256);assert.equal(sha,m.visualAcceptanceRecord?.sha256||m.visualAcceptanceRecord?.assetSha256);assert.match(m.visualAcceptance,/accepted|approved/);return{id:m.id,sha256:sha,status:m.visualAcceptance};});
function walkableConnection(plan,a,b){const n=Math.ceil(Math.hypot(a.x-b.x,a.z-b.z)/.08);for(let i=0;i<=n;i++){const u=n?i/n:0;if(!canOccupy(plan,a.x+(b.x-a.x)*u,a.z+(b.z-a.z)*u,.30))return false;}return true;}
function reachable(plan,start,targets){const step=.25,key=(x,z)=>x+','+z,startCell={x:Math.round(start.x/step),z:Math.round(start.z/step)},queue=[startCell],seen=new Set([key(startCell.x,startCell.z)]);assert.ok(walkableConnection(plan,start,{x:startCell.x*step,z:startCell.z*step}));
 for(let head=0;head<queue.length;head++){const p=queue[head];for(const [dx,dz] of[[1,0],[-1,0],[0,1],[0,-1]]){const x=p.x+dx,z=p.z+dz,k=key(x,z);if(seen.has(k)||x<-40||x>40||z<-140||z>-52)continue;if(!walkableConnection(plan,{x:p.x*step,z:p.z*step},{x:x*step,z:z*step}))continue;seen.add(k);queue.push({x,z});}}
 return targets.map(p=>{const near={x:Math.round(p.x/step),z:Math.round(p.z/step)};return seen.has(key(near.x,near.z))&&walkableConnection(plan,{x:near.x*step,z:near.z*step},p);});}
function boxDistance(c,x,z){const dx=x-c.x,dz=z-c.z,co=Math.cos(c.rotation||0),si=Math.sin(c.rotation||0);return Math.hypot(Math.max(0,Math.abs(dx*co-dz*si)-c.w/2),Math.max(0,Math.abs(dx*si+dz*co)-c.d/2));}
const records=[];
for(const id of['residential','market','workshops']){const spec=JSON.parse(fs.readFileSync(new URL('../public/data/v4/'+id+'.json',import.meta.url))),plan=compileTown(spec),stage=makeCastStage();assert.deepEqual(plan.castStage,stage);assert.equal(plan.props.length,5);assert.deepEqual(plan.people.map(p=>p.species),['moogle','chocobo','mage']);assert.ok(canOccupy(plan,stage.camera.x,stage.camera.z,.30));
 const views=plan.people.map(p=>p.view||{x:p.x+(p.species==='moogle'?.68:.55),z:p.z+(p.species==='moogle'?2.15:2.90)});for(const view of views)assert.ok(canOccupy(plan,view.x,view.z,.30));assert.ok(reachable(plan,stage.camera,views).every(Boolean),'all roles reachable '+id);
 for(const p of plan.props){assert.ok(plan.colliders.some(c=>c.id===p.id));assert.ok(!canOccupy(plan,p.x,p.z));}
 for(const b of plan.colliders.filter(c=>c.id.startsWith('bench-')))assert.ok(boxDistance(b,-1,-24)>2.45,'bench clear of fountain');const table=plan.props.find(p=>p.kind==='bookTable');assert.ok(Math.hypot(table.x+1,table.z+24)-table.r>2.45,'table separated from fountain');
 const postal=plan.people[0],safe={...plan,colliders:plan.colliders.filter(c=>c.id!=='person-0')};for(let z=postal.z;z<=postal.z+1.25;z+=.05)assert.ok(canOccupy(safe,postal.x,z,.26),'postal patrol corridor');
 records.push({id,stage:stage.id,props:plan.props.map(p=>p.kind),roles:plan.people.map(p=>({species:p.species,role:p.role,x:p.x,z:p.z,facing:p.facing})),overviewClear:true,furnitureSeparatedFromFountain:true,viewpointsReachable:true,postalPatrolClear:true,pathLength:plan.length});}
const report={passed:true,modelsUnchanged:true,newImageGenerationCalls:0,models,records};fs.mkdirSync(new URL('../evidence/cast/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('../evidence/cast/verification.json',import.meta.url),JSON.stringify(report,null,2));console.log(report);
