import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {compileTown,canOccupy} from '../src/layout.js';import {createMoogleBehavior} from '../src/moogle-behavior.js';
const url=new URL('../public/assets/characters/moogle/moogle-courier-v3.glb',import.meta.url),buffer=fs.readFileSync(url);assert.equal(buffer.toString('utf8',0,4),'glTF');assert.equal(buffer.readUInt32LE(4),2);assert.equal(buffer.readUInt32LE(8),buffer.length);
const jsonLength=buffer.readUInt32LE(12),gltf=JSON.parse(buffer.subarray(20,20+jsonLength).toString().trim()),binary=buffer.subarray(20+jsonLength+8);
const sizes={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4},counts={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16};
function readAccessor(id){const a=gltf.accessors[id],v=gltf.bufferViews[a.bufferView],width=counts[a.type],size=sizes[a.componentType],stride=v.byteStride||width*size,offset=(v.byteOffset||0)+(a.byteOffset||0),view=new DataView(binary.buffer,binary.byteOffset,binary.byteLength),fn={5120:'getInt8',5121:'getUint8',5122:'getInt16',5123:'getUint16',5125:'getUint32',5126:'getFloat32'}[a.componentType],rows=[];for(let i=0;i<a.count;i++){const row=[];for(let j=0;j<width;j++){let x=view[fn](offset+i*stride+j*size,true);if(a.normalized)x/=a.componentType===5121?255:a.componentType===5123?65535:1;assert.ok(Number.isFinite(x));row.push(x);}rows.push(row);}return rows;}
assert.equal(gltf.skins.length,1);assert.equal(gltf.skins[0].joints.length,27);assert.deepEqual(gltf.animations.map(a=>a.name).sort(),['Deliver','Idle','Walk','Wave']);
let vertices=0,triangles=0;for(const mesh of gltf.meshes)for(const p of mesh.primitives){const weights=readAccessor(p.attributes.WEIGHTS_0),joints=readAccessor(p.attributes.JOINTS_0);for(let i=0;i<weights.length;i++){assert.ok(Math.abs(weights[i].reduce((a,b)=>a+b,0)-1)<.005);assert.ok(joints[i].every(j=>j>=0&&j<27));}vertices+=weights.length;triangles+=(p.indices!==undefined?gltf.accessors[p.indices].count:weights.length)/3;}
const clips=[];for(const a of gltf.animations){let seconds=0,changes=0,maxSeam=0;for(const c of a.channels){const sampler=a.samplers[c.sampler],times=readAccessor(sampler.input).flat(),values=readAccessor(sampler.output);assert.ok(times.every((t,i)=>i===0||t>times[i-1]));seconds=Math.max(seconds,times.at(-1));const first=values[0],last=values.at(-1);let seam=Math.max(...first.map((x,i)=>Math.abs(x-last[i])));if(c.target.path==='rotation'){for(const v of values)assert.ok(Math.abs(Math.hypot(...v)-1)<.006);seam=Math.min(seam,Math.max(...first.map((x,i)=>Math.abs(x+last[i]))));}maxSeam=Math.max(maxSeam,seam);if(values.some(v=>v.some((x,i)=>Math.abs(x-first[i])>.01)))changes++;}assert.ok(changes>=3,'clip must animate independent joints');if(['Idle','Walk'].includes(a.name))assert.ok(maxSeam<.002,'loop seam '+a.name+': '+maxSeam);clips.push({name:a.name,seconds,animatedChannels:changes,loopSeam:maxSeam});}
const build=JSON.parse(fs.readFileSync(new URL('../evidence/moogle/build-report.json',import.meta.url)));assert.ok(build.allWeightsNormalized);assert.equal(build.bodyConnectedComponents,1);assert.equal(build.bodyNonmanifoldEdges,0);assert.ok(build.strapEndCentersMatchRingCenters);for(const s of Object.values(build.sampledJointStrain)){assert.ok(s.p99Stretch<2);assert.ok(s.p01Compression>.45);}for(const c of Object.values(build.sampledGroundContacts))assert.ok(c.minimumBodyZ>-.002,'ground penetration');
for(const c of Object.values(build.sampledSurfaceIntersections)){assert.ok(c.frames>=20);assert.equal(c.armHeadSurfacePairs,0,'arm crosses head');assert.equal(c.armBagSurfacePairs,0,'arm crosses bag');assert.equal(c.letterHeadSurfacePairs,0,'letter crosses head');}
const behaviorRecords=[];for(const id of['residential','market','workshops']){const plan=compileTown(JSON.parse(fs.readFileSync(new URL('../public/data/v4/'+id+'.json',import.meta.url)))),index=plan.people.findIndex(p=>p.species==='moogle'),p=plan.people[index];let clip='Idle',finished=null,delivered=0;const root={position:{x:p.x,z:p.z},rotation:{y:0}},actor={root,play(name){clip=name;},update(){},consumeFinished(){const v=finished;finished=null;return v;},snapshot(){return{clip,position:{...root.position}};}};const ctl=createMoogleBehavior(actor,plan,index,{onDelivered:()=>delivered++});const far={x:0,z:30};for(let i=0;i<180;i++)ctl.update(.05,far);assert.ok(Math.abs(root.position.z-p.z)>.1,'courier must actually walk');const own=plan.colliders.find(c=>c.id==='person-'+index);assert.equal(own.z,root.position.z);assert.ok(!ctl.deliver(far),'cannot deliver from distant player');const near={x:root.position.x+.8,z:root.position.z+1.3};ctl.update(.05,near);assert.equal(ctl.snapshot().state,'wave');assert.ok(ctl.deliver(near));assert.equal(clip,'Deliver');finished='Deliver';ctl.update(.05,near);assert.equal(delivered,1);assert.equal(ctl.snapshot().state,'idle');assert.ok(ctl.snapshot().waiting);const approachingPlayer={x:root.position.x,z:root.position.z+2.8};const approachingCtl=createMoogleBehavior(actor,plan,index);const oldZ=root.position.z;for(let i=0;i<200;i++)approachingCtl.update(.05,approachingPlayer);assert.ok(root.position.z>oldZ+.3,'must approach the nearby player');behaviorRecords.push({id,walking:true,approachesPlayer:true,colliderSynchronized:true,nearGreeting:true,localDelivery:true});}
const report={passed:true,assetSha256:createHash('sha256').update(buffer).digest('hex'),bytes:buffer.length,skinCount:1,joints:27,meshes:gltf.meshes.length,vertices,triangles,embeddedImages:gltf.images.length,clips,allWeightsNormalized:true,bodyConnectedComponents:build.bodyConnectedComponents,bodyNonmanifoldEdges:build.bodyNonmanifoldEdges,jointStrain:build.sampledJointStrain,groundSamples:build.sampledGroundContacts,surfaceIntersections:build.sampledSurfaceIntersections,behaviorRecords,sharedAssetInThreeStreets:true};fs.writeFileSync(new URL('../evidence/moogle/asset-verification.json',import.meta.url),JSON.stringify(report,null,2));console.log(report);
