import './moogle-studio.css';
import './royal-studio.css';
const targets={steiner:new URL('../art-direction/royal-cast/steiner-target-v1.png',import.meta.url).href,zidane:new URL('../art-direction/royal-cast/zidane-target-v1.png',import.meta.url).href,garnet:new URL('../art-direction/royal-cast/garnet-target-v1.png',import.meta.url).href};
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {royalLoaders,loadSteinerV4,loadGarnetV3,createRoyal,ROYAL_CAST as OLD_CAST} from './royal-cast.js';
const rebuildId=location.pathname.endsWith('/garnet.html')?'garnet':location.pathname.endsWith('/steiner.html')?'steiner':null;
const rebuilding=Boolean(rebuildId);
const studies={steiner:{height:2.08,version:4,distance:3.65,faceY:1.46,loader:loadSteinerV4,description:'再收小脸部，重塑下颌、颧骨和眉眼。头部修订样本，尚待验收。'},garnet:{height:1.80,version:3,distance:3.20,faceY:1.63,loader:loadGarnetV3,description:'重新构建女性脸型、眼窝与鼻唇结构。脸部修订样本，尚待验收。',signature:'轻轻点头，向路过的人致意。'}};
const ROYAL_CAST=rebuilding?{[rebuildId]:{...OLD_CAST[rebuildId],...studies[rebuildId]}}:OLD_CAST;
const $=s=>document.querySelector(s),canvas=$('#portrait');
try{
 await Promise.all(Object.values(rebuilding?{[rebuildId]:studies[rebuildId].loader}:royalLoaders).map(load=>load()));const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 const scene=new THREE.Scene();scene.background=new THREE.Color(0xe8e0d2);const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.025);scene.environment=env.texture;scene.environmentIntensity=.65;room.dispose();pmrem.dispose();scene.add(new THREE.HemisphereLight(0xe9f0f3,0xb8a480,1.2));const sun=new THREE.DirectionalLight(0xffe5c4,3.0);sun.position.set(-2.4,4.5,3);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-2,right:2,top:3,bottom:-2,near:.1,far:12});sun.shadow.normalBias=.006;sun.shadow.bias=-.00007;scene.add(sun);const fill=new THREE.DirectionalLight(0xb8c8db,.6);fill.position.set(2,2,-1);scene.add(fill);const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0xe2d8c3,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.004;floor.receiveShadow=true;scene.add(floor);
 const actors=Object.fromEntries(Object.keys(ROYAL_CAST).map(id=>{const a=createRoyal(id);scene.add(a.root);a.root.visible=false;return[id,a];}));const camera=new THREE.PerspectiveCamera(40,1,.03,30),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=1.5;controls.maxDistance=7;controls.maxPolarAngle=Math.PI*.53;
 const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const ao=new SSAOPass(scene,camera,innerWidth,innerHeight,16);ao.kernelRadius=.12;ao.minDistance=.00008;ao.maxDistance=.035;composer.addPass(ao);composer.addPass(new OutputPass());let id=rebuildId||'steiner',actor=null,angle='front',all=false;
 function fit(name=angle){angle=name;if(name==='face'){controls.maxDistance=7;const y=studies[id]?.faceY||1.46;controls.target.set(0,y,0);camera.position.set(.05,y,1.6);controls.update();return;}controls.maxDistance=innerWidth<=760?13:(all?12:7);const h=all?2.19:ROYAL_CAST[id].height,r=all?(innerWidth<=760?10.5:5.2):(innerWidth<=760?(rebuilding?10.4:9.5):rebuilding?studies[id].distance:3.6);controls.target.set(0,h*.48,0);camera.position.set(name==='side'?r:name==='back'?0:rebuilding?0:.72,h*.52,name==='side'?.06:name==='back'?-r:r);controls.update();}
 let wasMobile=null;function resize(){renderer.setSize(innerWidth,innerHeight,false);composer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();camera.setViewOffset(innerWidth,innerHeight,innerWidth>760?115:0,innerWidth>760?0:80,innerWidth,innerHeight);const mobile=innerWidth<=760;if(mobile!==wasMobile){wasMobile=mobile;fit();}}addEventListener('resize',resize);resize();
 function clip(name){if(all)Object.values(actors).forEach(a=>a.play(name));else actor.play(name);document.querySelectorAll('[data-clip]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.clip===name)));$('#freeze').setAttribute('aria-pressed','false');$('#action-note').textContent=name==='Signature'?ROYAL_CAST[id].signature:{Idle:'呼吸与轻轻转头。',Walk:'身体、手臂、衣服和配件随步伐运动。',Greet:'向路过的人打一个招呼。'}[name];}
 function choose(next){if(!actors[next])return;all=false;$('#all-cast').setAttribute('aria-pressed','false');$('#reference').disabled=false;$('#reference').textContent=rebuilding?(id==='garnet'?'看造型素材图 ↗':'看头部素材图 ↗'):'看 '+next+' 目标图 ↗';id=next;actor=actors[id];Object.values(actors).forEach(a=>a.root.position.x=0);Object.values(actors).forEach(a=>a.root.visible=a===actor);$('#hero-name').textContent=ROYAL_CAST[id].name;$('#hero-description').textContent=rebuilding?ROYAL_CAST[id].description:'旧版未通过，保留为造型对照。';document.querySelectorAll('[data-character]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.character===id)));clip('Idle');fit('front');$('#art-image').src=targets[id];history.replaceState(null,'','?character='+id);}
 $('#all-cast').addEventListener('click',()=>{all=true;$('#all-cast').setAttribute('aria-pressed','true');document.querySelectorAll('[data-character]').forEach(b=>b.setAttribute('aria-pressed','false'));$('#reference').disabled=true;Object.values(actors).forEach((a,i)=>{a.root.visible=true;a.root.position.x=(i-1)*1.05;});$('#hero-name').textContent='王城的三位朋友';$('#hero-description').textContent='未通过的旧版，保留为失败对照。';clip('Idle');fit('front');history.replaceState(null,'','?character=all');});
 document.querySelectorAll('[data-character]').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.character)));document.querySelectorAll('[data-clip]').forEach(b=>b.addEventListener('click',()=>clip(b.dataset.clip)));$('#freeze').addEventListener('click',()=>{const value=!actor.snapshot().frozen;if(all)Object.values(actors).forEach(a=>a.freeze(value));else actor.freeze(value);$('#freeze').setAttribute('aria-pressed',String(value));});$('#pose-frame').addEventListener('input',()=>{if(all)Object.values(actors).forEach(a=>a.seek(Number($('#pose-frame').value)/100));else actor.seek(Number($('#pose-frame').value)/100);$('#freeze').setAttribute('aria-pressed','true');});for(const name of rebuilding?['front','side','back','face']:['front','side','back'])$('#'+name).addEventListener('click',()=>fit(name));$('#reference').addEventListener('click',()=>$('#art-dialog').showModal());$('#art-close').addEventListener('click',()=>$('#art-dialog').close());const requested=rebuilding?rebuildId:new URLSearchParams(location.search).get('character')||'steiner';choose(requested==='all'?'steiner':requested);if(requested==='all')$('#all-cast').click();$('#loading').hidden=true;let last=performance.now();function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(all)Object.values(actors).forEach(a=>a.update(dt));else actor.update(dt);controls.update();composer.render();$('#royal-state').dataset.ready='true';$('#royal-state').textContent=JSON.stringify(all?{id:'all',actors:Object.values(actors).map(a=>a.snapshot()),view:angle}:{...actor.snapshot(),version:rebuilding?studies[id].version:1,artStatus:rebuilding?'pending':'rejected',view:angle});requestAnimationFrame(frame);}requestAnimationFrame(frame);
}catch(e){$('#loading').hidden=false;$('#loading').textContent=e.message;console.error(e);}
